// <auto-generated />
using System;
using CourseRegistrationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseRegistrationSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405060648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseRegistrationSystem.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "SectionId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            FacultyId = "F_IT",
                            FacultyName = "Khoa Công nghệ Thông tin 2"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LecturerId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            LecturerId = "L_KIEN",
                            Degree = "Thạc sĩ",
                            FacultyId = "F_IT",
                            UserId = "U_KIEN"
                        },
                        new
                        {
                            LecturerId = "L_HIEU",
                            Degree = "Tiến sĩ",
                            FacultyId = "F_IT",
                            UserId = "U_HIEU"
                        },
                        new
                        {
                            LecturerId = "L_THE",
                            Degree = "Thạc sĩ",
                            FacultyId = "F_IT",
                            UserId = "U_THE"
                        },
                        new
                        {
                            LecturerId = "L_HAO",
                            Degree = "Thạc sĩ",
                            FacultyId = "F_IT",
                            UserId = "U_HAO"
                        },
                        new
                        {
                            LecturerId = "L_HOANG",
                            Degree = "Tiến sĩ",
                            FacultyId = "F_IT",
                            UserId = "U_HOANG"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.RegistrationPeriod", b =>
                {
                    b.Property<string>("PeriodId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PeriodId");

                    b.HasIndex("SemesterId");

                    b.ToTable("RegistrationPeriods");

                    b.HasData(
                        new
                        {
                            PeriodId = "REG_HK2_2324",
                            EndTime = new DateTime(2028, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            PeriodName = "Đăng ký tín chỉ HK2 - Khóa 2022",
                            SemesterId = "HK2_2324",
                            StartTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TargetAudience = "D22CQCN"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = "R_STUDENT",
                            RoleName = "Student"
                        },
                        new
                        {
                            RoleId = "R_LECTURER",
                            RoleName = "Lecturer"
                        },
                        new
                        {
                            RoleId = "R_ADMIN",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Schedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodCount")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("StartPeriod")
                        .HasColumnType("integer");

                    b.HasKey("ScheduleId");

                    b.HasIndex("SectionId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = "SCH_01",
                            DayOfWeek = 2,
                            PeriodCount = 4,
                            Room = "2A33",
                            SectionId = "SEC_INT1461_01",
                            StartPeriod = 1
                        },
                        new
                        {
                            ScheduleId = "SCH_02",
                            DayOfWeek = 2,
                            PeriodCount = 4,
                            Room = "2A27",
                            SectionId = "SEC_INT1449_03",
                            StartPeriod = 5
                        },
                        new
                        {
                            ScheduleId = "SCH_03",
                            DayOfWeek = 4,
                            PeriodCount = 4,
                            Room = "HTD",
                            SectionId = "SEC_INT1448_01",
                            StartPeriod = 1
                        },
                        new
                        {
                            ScheduleId = "SCH_04",
                            DayOfWeek = 4,
                            PeriodCount = 4,
                            Room = "2A33",
                            SectionId = "SEC_INT1416_01",
                            StartPeriod = 5
                        },
                        new
                        {
                            ScheduleId = "SCH_05",
                            DayOfWeek = 4,
                            PeriodCount = 4,
                            Room = "HTD",
                            SectionId = "SEC_INT1427_01",
                            StartPeriod = 9
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Section", b =>
                {
                    b.Property<string>("SectionId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("RegisteredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SectionId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = "SEC_INT1461_01",
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerId = "L_KIEN",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            SemesterId = "HK2_2324",
                            SubjectId = "INT1461"
                        },
                        new
                        {
                            SectionId = "SEC_INT1449_03",
                            GroupNumber = 3,
                            IsActive = true,
                            LecturerId = "L_HIEU",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            SemesterId = "HK2_2324",
                            SubjectId = "INT1449"
                        },
                        new
                        {
                            SectionId = "SEC_INT1448_01",
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerId = "L_THE",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            SemesterId = "HK2_2324",
                            SubjectId = "INT1448"
                        },
                        new
                        {
                            SectionId = "SEC_INT1416_01",
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerId = "L_HAO",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            SemesterId = "HK2_2324",
                            SubjectId = "INT1416"
                        },
                        new
                        {
                            SectionId = "SEC_INT1427_01",
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerId = "L_HOANG",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            SemesterId = "HK2_2324",
                            SubjectId = "INT1427"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Semester", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            SemesterId = "HK2_2324",
                            AcademicYear = "2023-2024",
                            SemesterName = "Học kỳ 2"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "1",
                            ClassId = "D22CQCN01-N",
                            UserId = "U_KHOI"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.StudentClass", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClassId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = "D22CQCN01-N",
                            AcademicYear = "2022-2026",
                            ClassName = "D22CQCN01-N",
                            EducationType = "Đại học chính quy",
                            FacultyId = "F_IT"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SubjectId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = "INT1461",
                            Credits = 3,
                            FacultyId = "F_IT",
                            SubjectName = "Xây dựng các hệ thống nhúng"
                        },
                        new
                        {
                            SubjectId = "INT1449",
                            Credits = 3,
                            FacultyId = "F_IT",
                            SubjectName = "Phát triển ứng dụng cho các thiết bị di động"
                        },
                        new
                        {
                            SubjectId = "INT1448",
                            Credits = 3,
                            FacultyId = "F_IT",
                            SubjectName = "Phát triển phần mềm hướng dịch vụ"
                        },
                        new
                        {
                            SubjectId = "INT1416",
                            Credits = 3,
                            FacultyId = "F_IT",
                            SubjectName = "Đảm bảo chất lượng phần mềm"
                        },
                        new
                        {
                            SubjectId = "INT1427",
                            Credits = 3,
                            FacultyId = "F_IT",
                            SubjectName = "Kiến trúc và thiết kế phần mềm"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "U_KHOI",
                            Address = "97 Man Thiện, P. Hiệp Phú, TP. Thủ Đức, TP.HCM",
                            DateOfBirth = new DateOnly(2004, 5, 15),
                            Email = "khoipd@student.ptithcm.edu.vn",
                            FullName = "Phạm Đăng Khôi",
                            Gender = 0,
                            IsActive = true,
                            NationalId = "079123456789",
                            Password = "hashed_password",
                            PhoneNumber = "0901234567",
                            RoleId = "R_STUDENT",
                            Username = "khoipd_ptit"
                        },
                        new
                        {
                            UserId = "U_KIEN",
                            Address = "Q. Bình Thạnh, TP.HCM",
                            DateOfBirth = new DateOnly(1985, 1, 1),
                            Email = "kiennt@ptithcm.edu.vn",
                            FullName = "Nguyễn Trọng Kiên",
                            Gender = 0,
                            IsActive = true,
                            NationalId = "079222222221",
                            Password = "hashed_password",
                            PhoneNumber = "0902222221",
                            RoleId = "R_LECTURER",
                            Username = "kiennt"
                        },
                        new
                        {
                            UserId = "U_HIEU",
                            Address = "Q. 9, TP.HCM",
                            DateOfBirth = new DateOnly(1988, 2, 2),
                            Email = "hieunt@ptithcm.edu.vn",
                            FullName = "Nguyễn Trung Hiếu",
                            Gender = 0,
                            IsActive = true,
                            NationalId = "079333333332",
                            Password = "hashed_password",
                            PhoneNumber = "0903333332",
                            RoleId = "R_LECTURER",
                            Username = "hieunt"
                        },
                        new
                        {
                            UserId = "U_THE",
                            Address = "Q. Gò Vấp, TP.HCM",
                            DateOfBirth = new DateOnly(1987, 3, 3),
                            Email = "thept@ptithcm.edu.vn",
                            FullName = "Phan Thị Thể",
                            Gender = 1,
                            IsActive = true,
                            NationalId = "079444444443",
                            Password = "hashed_password",
                            PhoneNumber = "0904444443",
                            RoleId = "R_LECTURER",
                            Username = "thept"
                        },
                        new
                        {
                            UserId = "U_HAO",
                            Address = "Q. Thủ Đức, TP.HCM",
                            DateOfBirth = new DateOnly(1990, 4, 4),
                            Email = "haona@ptithcm.edu.vn",
                            FullName = "Nguyễn Anh Hào",
                            Gender = 0,
                            IsActive = true,
                            NationalId = "079555555554",
                            Password = "hashed_password",
                            PhoneNumber = "0905555554",
                            RoleId = "R_LECTURER",
                            Username = "haona"
                        },
                        new
                        {
                            UserId = "U_HOANG",
                            Address = "Q. 10, TP.HCM",
                            DateOfBirth = new DateOnly(1982, 5, 5),
                            Email = "hoangnvh@ptithcm.edu.vn",
                            FullName = "Nguyễn Văn Hữu Hoàng",
                            Gender = 0,
                            IsActive = true,
                            NationalId = "079666666665",
                            Password = "hashed_password",
                            PhoneNumber = "0906666665",
                            RoleId = "R_LECTURER",
                            Username = "hoangnvh"
                        });
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Enrollment", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseRegistrationSystem.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Lecturer", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Faculty", "Faculty")
                        .WithMany("Lecturers")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseRegistrationSystem.Models.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("CourseRegistrationSystem.Models.Lecturer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.RegistrationPeriod", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Semester", "Semester")
                        .WithMany("RegistrationPeriods")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Schedule", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Section", "Section")
                        .WithMany("Schedules")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Section", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Lecturer", "Lecturer")
                        .WithMany("Sections")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseRegistrationSystem.Models.Semester", "Semester")
                        .WithMany("Sections")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseRegistrationSystem.Models.Subject", "Subject")
                        .WithMany("Sections")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Student", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.StudentClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseRegistrationSystem.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("CourseRegistrationSystem.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.StudentClass", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Faculty", "Faculty")
                        .WithMany("Classes")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Subject", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.User", b =>
                {
                    b.HasOne("CourseRegistrationSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Faculty", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Lecturers");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Lecturer", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Section", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Semester", b =>
                {
                    b.Navigation("RegistrationPeriods");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.StudentClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.Subject", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("CourseRegistrationSystem.Models.User", b =>
                {
                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
