// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTinChi.Data;

#nullable disable

namespace TinChiComp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408132413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("QuanLyTinChi.Models.Section", b =>
                {
                    b.Property<string>("SectionId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisteredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ScheduleInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SectionId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = "SEC_INT1461_01",
                            Credits = 3,
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerName = "Nguyễn Văn A",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            ScheduleInfo = "Thứ 2, 1-4, P.101",
                            SemesterName = "Học kỳ 1",
                            SubjectId = "INT1461",
                            SubjectName = "Xây dựng các hệ thống nhúng"
                        },
                        new
                        {
                            SectionId = "SEC_INT1449_03",
                            Credits = 3,
                            GroupNumber = 3,
                            IsActive = true,
                            LecturerName = "Trần Thị B",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            ScheduleInfo = "Thứ 3, 5-8, P.102",
                            SemesterName = "Học kỳ 1",
                            SubjectId = "INT1449",
                            SubjectName = "Phát triển ứng dụng cho các thiết bị di động"
                        },
                        new
                        {
                            SectionId = "SEC_INT1448_01",
                            Credits = 3,
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerName = "Lê Văn C",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            ScheduleInfo = "Thứ 4, 1-4, P.103",
                            SemesterName = "Học kỳ 1",
                            SubjectId = "INT1448",
                            SubjectName = "Phát triển phần mềm hướng dịch vụ"
                        },
                        new
                        {
                            SectionId = "SEC_INT1416_01",
                            Credits = 3,
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerName = "Phạm Thị D",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            ScheduleInfo = "Thứ 5, 5-8, P.104",
                            SemesterName = "Học kỳ 1",
                            SubjectId = "INT1416",
                            SubjectName = "Đảm bảo chất lượng phần mềm"
                        },
                        new
                        {
                            SectionId = "SEC_INT1427_01",
                            Credits = 3,
                            GroupNumber = 1,
                            IsActive = true,
                            LecturerName = "Vũ Văn E",
                            MaxCapacity = 80,
                            RegisteredCount = 0,
                            ScheduleInfo = "Thứ 6, 1-4, P.105",
                            SemesterName = "Học kỳ 1",
                            SubjectId = "INT1427",
                            SubjectName = "Kiến trúc và thiết kế phần mềm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
